<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Password;
use AppBundle\Entity\User;
use Doctrine\Common\Collections\Criteria;

/**
 * PasswordRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param array $groupIds
     *
     * @return mixed
     */
    public function findByGroups(array $groupIds = [])
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->join('p.groups', 'g')
            ->where('g.id IN (:groupIds)')
            ->orderBy('p.updatedAt', Criteria::DESC)
            ->setParameter('groupIds', $groupIds)
            ->getQuery()
            ->execute();
    }

    /**
     * @param Password $password
     * @param User     $user
     */
    public function removeByUser(Password $password, User $user)
    {
        if ($password->getGroups()->count() > 1) {
            $password->removeGroup($user->getPrivateGroup());
            $this->getEntityManager()->persist($password);
        } else {
            $this->getEntityManager()->remove($password);
        }
    }
}
